esphome:
  name: zmai_90_test

esp8266:
  board: esp01_1m

external_components:
  - source:
      type: local
      path: ./components/
    components: [zmai90]

uart:
  rx_pin: 3
  tx_pin: 1
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  stop_bits: 1 
  id: uart_bus

sensor:
  - platform: zmai90
    update_interval: 10s
    voltage:
      name: "Voltage"
    current:
      name: "Current"
    frequency:
      name: "Frequency"
    active_power:
      name: "Active Power"
    reactive_power:
      name: "Reactive Power"
    apparent_power:
      name: "Apparent Power"
    power_factor:
      name: "Power Factor"
    consumed_energy:
      name: "Consumed Energy"


#send request for data
#interval:
#  - interval: 10s
#    then:
#      - uart.write: [0xfe, 0x01, 0x0f, 0x08, 0x00, 0x00, 0x00, 0x1c]
